"use client";
import { useState } from "react";
import { attendanceDay, filterAttendance } from "./attendance-utils.mjs";
type Activity = {id:string;clientId:string;clientName:string;type:"registro"|"visita"|"premio";description:string;createdAt:string};
type Member = {id:string;name:string;phone:string;photo:string;plan:string;expiresAt:string;visits:number;accessStatus:string;balance:number};
type Props = {activities:Activity[];clients:Member[];onScan:()=>void;onVisit:(id:string)=>void;onCard:(id:string)=>void;onPay:(id:string)=>void;onEdit:(id:string)=>void};
const date = (value:string) => new Intl.DateTimeFormat("es-BO",{timeZone:"America/La_Paz",day:"2-digit",month:"short",year:"numeric"}).format(new Date(value));
const time = (value:string) => new Intl.DateTimeFormat("es-BO",{timeZone:"America/La_Paz",hour:"2-digit",minute:"2-digit"}).format(new Date(value));
const labels:Record<string,string>={active:"Activo",expired:"Vencido",manual_suspended:"Suspendido",debt_suspended:"Con deuda",sessions_exhausted:"Sin sesiones"};
function Photo({client,name}:{client?:Member;name:string}){return client?.photo?<img src={client.photo} alt={`Foto de ${name}`}/>:<span className="attendance-avatar">{name.split(" ").map(part=>part[0]).join("").slice(0,2)}</span>;}
function ScanIcon(){return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M3 8V3h5m8 0h5v5m0 8v5h-5M8 21H3v-5M9 9h6v6H9z"/></svg>;}
export function AttendanceView({activities,clients,onScan,onVisit,onCard,onPay,onEdit}:Props){
  const [period,setPeriod]=useState("all");const [query,setQuery]=useState("");const [type,setType]=useState("all");const [filterOpen,setFilterOpen]=useState(false);const [clientId,setClientId]=useState("");
  const [selected,setSelected]=useState<Activity|null>(null);const [manual,setManual]=useState(false);const [manualQuery,setManualQuery]=useState("");
  const filtered=filterAttendance(activities,clients,{period,query,type,clientId}) as Activity[];
  const groups=new Map<string,Activity[]>();for(const item of filtered){const day=attendanceDay(item.createdAt);groups.set(day,[...(groups.get(day)||[]),item]);}
  const member=selected?clients.find(c=>c.id===selected.clientId):undefined;
  const today=attendanceDay(new Date());
  function openRecord(item:Activity){setSelected(item);window.scrollTo({top:0,behavior:"instant"});}
  function openManual(){setManual(true);setManualQuery("");window.scrollTo({top:0,behavior:"instant"});}
  function reset(){setPeriod("all");setQuery("");setType("all");setClientId("");}
  if(manual)return <section className="attendance-page"><header className="attendance-detail-heading"><button onClick={()=>setManual(false)} aria-label="Volver a asistencias">‹</button><h1>Registrar manualmente</h1></header><div className="attendance-panel"><h2>Selecciona al cliente</h2><p>Validaremos su membresía antes de confirmar el ingreso.</p><label className="attendance-search">Buscar cliente<input value={manualQuery} onChange={e=>setManualQuery(e.target.value)} placeholder="Nombre o teléfono"/></label><div className="attendance-manual-list">{clients.filter(c=>`${c.name} ${c.phone}`.toLowerCase().includes(manualQuery.toLowerCase())).map(c=><button key={c.id} onClick={()=>onVisit(c.id)}><Photo client={c} name={c.name}/><span><strong>{c.name}</strong><small>{c.phone} · {labels[c.accessStatus]}</small></span><b>›</b></button>)}</div>{!clients.some(c=>`${c.name} ${c.phone}`.toLowerCase().includes(manualQuery.toLowerCase()))&&<p>No hay clientes que coincidan con la búsqueda.</p>}</div></section>;
  if(selected)return <section className="attendance-page"><header className="attendance-detail-heading"><button onClick={()=>setSelected(null)} aria-label="Volver al historial">‹</button><h1>Detalle de asistencia</h1></header><div className="attendance-detail-grid"><article className="attendance-panel"><div className="attendance-person"><Photo client={member} name={member?.name||selected.clientName}/><div><h2>{member?.name||selected.clientName}</h2><p>{member?.phone||"Cliente no disponible"}</p></div>{member&&<span className={`attendance-state ${member.accessStatus}`}>{labels[member.accessStatus]}</span>}</div><div className="attendance-person-actions"><button disabled={!member} onClick={()=>member&&onCard(member.id)}>▣<span>Tarjeta</span></button><button onClick={()=>{reset();setClientId(selected.clientId);setSelected(null);}}>◷<span>Historial</span></button><button disabled={!member} onClick={()=>member&&onPay(member.id)}>$<span>Cobrar</span></button><button disabled={!member} onClick={()=>member&&onEdit(member.id)}>⋯<span>Editar</span></button></div></article><article className="attendance-panel attendance-record"><div className="attendance-event"><span className={`attendance-event-icon ${selected.type}`}>{selected.type==="registro"?"+":"✓"}</span><div><h2>{selected.type==="registro"?"Cliente registrado":selected.type==="premio"?"Visita con premio":"Visita registrada"}</h2><p>{date(selected.createdAt)}, {time(selected.createdAt)}</p></div></div><p className="attendance-description">{selected.description}</p>{member&&<><div className="attendance-plan"><span>◇</span><div><small>Membresía actual</small><strong>Plan {member.plan}</strong><p>Vence {date(member.expiresAt)}</p></div></div><div className="attendance-progress-label"><span>Visitas al gym</span><strong>{member.visits} visita{member.visits === 1 ? "" : "s"}</strong></div><div className="attendance-encouragement"><strong>✦ ¡Sigamos así!</strong><p>La constancia construye grandes cambios.</p></div></>}</article><article className="attendance-panel attendance-information"><h2>Información del registro</h2><dl><div><dt>Tipo de movimiento</dt><dd>{selected.type==="registro"?"Alta de cliente":selected.type==="premio"?"Entrada con premio":"Entrada"}</dd></div><div><dt>Fecha</dt><dd>{date(selected.createdAt)}</dd></div><div><dt>Zona horaria</dt><dd>Bolivia (UTC−4)</dd></div><div><dt>Referencia</dt><dd>{selected.id.slice(0,8)}</dd></div></dl></article></div></section>;
  return <section className="attendance-page"><header className="attendance-heading"><div><h1>Asistencias</h1><p>Controla el acceso de tus clientes.</p></div><button className="attendance-primary" onClick={onScan}><ScanIcon/>Escanear QR</button></header><div className="attendance-filter-bar"><div className="attendance-tabs" aria-label="Período del historial">{[["all","Todas"],["today","Hoy"],["week","Esta semana"],["month","Este mes"]].map(([value,label])=><button key={value} aria-pressed={period===value} onClick={()=>setPeriod(value)}>{label}</button>)}</div><button className="attendance-filter-toggle" aria-label="Filtrar por tipo de movimiento" aria-expanded={filterOpen} onClick={()=>setFilterOpen(!filterOpen)}>☷</button></div>{filterOpen&&<label className="attendance-type-filter">Tipo de movimiento<select value={type} onChange={e=>setType(e.target.value)}><option value="all">Todos los movimientos</option><option value="visita">Visitas</option><option value="registro">Clientes registrados</option><option value="premio">Visitas con premio</option></select></label>}<label className="attendance-search"><span aria-hidden="true">⌕</span><input aria-label="Buscar en asistencias" placeholder="Buscar por nombre, teléfono o plan…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{clientId&&<div className="attendance-client-filter">Historial de {clients.find(c=>c.id===clientId)?.name||"cliente"}<button onClick={()=>setClientId("")}>Mostrar todos ×</button></div>}
    {filtered.length?<><div className="attendance-history">{Array.from(groups).map(([day,items])=><section key={day}><div className="attendance-day-heading"><h2>{day===today?"HOY · ":""}{date(`${day}T12:00:00-04:00`)}</h2><span>{items.length} registros</span></div><div className="attendance-panel attendance-list">{items.map(item=><button className="attendance-row" key={item.id} onClick={()=>openRecord(item)}><Photo client={clients.find(c=>c.id===item.clientId)} name={item.clientName}/><span className={`attendance-row-symbol ${item.type}`}>{item.type==="registro"?"+":"✓"}</span><span className="attendance-row-copy"><strong>{item.clientName}</strong><small>{item.description}</small></span><time dateTime={item.createdAt}>{time(item.createdAt)}</time><b>›</b></button>)}</div></section>)}</div><button className="attendance-banner" onClick={openManual}><span>♛</span><div><strong>Mantén la constancia de tus clientes</strong><small>Registrar un ingreso manualmente</small></div><b>›</b></button><p className="attendance-history-note">{filtered.length} movimientos visibles · historial reciente de hasta 1.000 registros.</p></>:<div className="attendance-empty"><div className="attendance-empty-icon"><ScanIcon/></div><h2>{query||type!=="all"||clientId?"No hay coincidencias":period==="today"?"Aún no hay asistencias hoy":"Aún no hay registros en este período"}</h2><p>{query||type!=="all"||clientId?"Prueba con otro nombre, tipo o período.":"Cuando registres un ingreso, aparecerá aquí."}</p><button className="attendance-primary" onClick={onScan}><ScanIcon/>Escanear QR</button><button onClick={openManual}>＋ Registrar manualmente</button>{(query||type!=="all"||period!=="all"||clientId)&&<button className="attendance-reset" onClick={reset}>Limpiar filtros</button>}</div>}</section>;
}
